version: "3"

services:
  app:
    image: aesirxio/content-app:latest
    environment:
      REACT_APP_CLIENT_ID: ${REACT_APP_CLIENT_ID}
      REACT_APP_CLIENT_SECRET: ${REACT_APP_CLIENT_SECRET}
      REACT_APP_ENDPOINT_URL: ${REACT_APP_ENDPOINT_URL}
      REACT_APP_ENCRYPT: ${REACT_APP_ENCRYPT}
      REACT_APP_LICENSE: ${REACT_APP_LICENSE}
      REACT_APP_TEST_MODE: ${REACT_APP_TEST_MODE}
      REACT_APP_SSO_CLIENT_ID: ${REACT_APP_SSO_CLIENT_ID}
      REACT_APP_SSO_CLIENT_SECRET: ${REACT_APP_SSO_CLIENT_SECRET}
      REACT_APP_DAM_LICENSE: ${REACT_APP_DAM_LICENSE}
    ports:
      - "${PORT-3000}:3000"