const FORM_FIELD_TYPE = {
  INPUT: 1,
  TEXTAREA: 2,
  CHECKBOX: 3,
  NUMBER: 4,
  DROPDOWN: 5,
  IMAGE: 6,
  DATE: 7,
  DATERANGE: 8,
  SELECTION: 9,
  TAB: 10,
  PASSWORD: 11,
  CANVA: 12,
  LABELCARD: 13,
  INFORMATION: 14,
  LABELBTN: 15,
  SELECTIONPERSONA: 16,
  DESCRIPTION: 17,
  DAM: 18,
  BIRTHDAY: 19,
  PRICE: 20,
  RADIO: 21,
  AGE: 22,
  LOCATION: 23,
  TIMEZONE: 24,
  EDITOR: 25,
  BUTTON: 26,
};

const FORMAT_DATE = 'yyyy-MM-dd';
const FORMAT_TIME = 'HH:mm:ss';

export { FORM_FIELD_TYPE, FORMAT_DATE, FORMAT_TIME };
